"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true


files: [
  {
    "source": "themes/ilhasoft/email/messages/messages_en.properties",
    "translation": "themes/ilhasoft/email/messages/messages_%locale%.properties",
  },
  {
    "source": "themes/ilhasoft/login/messages/messages_en.properties",
    "translation": "themes/ilhasoft/login/messages/messages_%locale%.properties",
  }
]