version: '3.6'

services:
  keycloak:
    image: ${DOCKER_IMAGE_NAME:-ilha/keycloak}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
      - ./themes/ilhasoft/:/opt/jboss/keycloak/themes/ilhasoft/
      # - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    networks:
      - keycloak

networks:
  keycloak:
    external: true
