name: Build Connect Keycloak in Dockerhub (Dispatch)

on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: 'Source branch in Connect Keycloak repository (main, staging, develop, fix/sentry etc.)'
        required: true
        default: 'main'
      tag-name:
        description: 'Tag id (v0.0.1-develop, v0.0.2, etc.)'
        required: true
      destination-env:
        description: 'Destination environment (develop, production, staging)'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set variables
        run: |
          echo "COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
          echo "COMMIT_SHA=${GITHUB_SHA}"
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}"
          echo "REGISTRY_URL=242357350604.dkr.ecr.sa-east-1.amazonaws.com" >> ${GITHUB_ENV}
          echo "REGISTRY_URL=242357350604.dkr.ecr.sa-east-1.amazonaws.com"
          echo "IMAGE_TAG=keycloak:$TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=keycloak:$TAG"
          echo "IMAGE_REPOSITORY=Ilhasoft/connect-keycloak" >> ${GITHUB_ENV}
          echo "IMAGE_REPOSITORY=Ilhasoft/connect-keycloak"
      
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.source-branch}}
          repository: Ilhasoft/connect-keycloak
          token: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to ECR
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY_URL }}
      #     username: ${{ secrets.AWS_ACCESS_KEY_ID_SP }}
      #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY_SP }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set Commit ID
        id: commit_id
        run: echo "::set-output commit=$(git rev-parse --short $GITHUB_SHA)"

      - name: Build and push - Connect Keycloak Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: branch=${{github.event.inputs.source-branch}},commit=${{env.GITHUB_SHA}},repository=https://github.com/Ilhasoft/connect-keycloak
          file: Dockerfile
          push: true
          tags: keycloak:${{github.event.inputs.tag-name}}
          no-cache: true
      
